# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170908_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='barcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
