# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170909_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
    ]
