# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170909_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDataTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_name', models.CharField(max_length=50, null=True)),
                ('audit_dttm', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(max_length=20)),
                ('upload_path', models.CharField(max_length=100)),
                ('ftp_host', models.CharField(max_length=50, null=True)),
                ('ftp_username', models.CharField(max_length=50, null=True)),
                ('ftp_port', models.CharField(max_length=6)),
                ('ftp_path', models.TextField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'request_data_track',
            },
        ),
    ]
